# Generated by Django 4.2.11 on 2025-01-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediacontent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mediacontent',
            name='title',
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='poster',
            field=models.URLField(default='https://via.placeholder.com/300'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='title_image',
            field=models.URLField(default='https://via.placeholder.com/150x50'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='transition_image',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
    ]
